# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Tumblr_Lab_October_2019' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Tumblr_Lab_October_2019

  pod 'AlamofireImage' 

  target 'Tumblr_Lab_October_2019Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Tumblr_Lab_October_2019UITests' do
    # Pods for testing
  end

end
